/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2018-11-02 12:32:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.other;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class clazzList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<title>班级列表</title>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/css/demo.css\">\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"easyui/js/validateExtends.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t$(function() {\t\n");
      out.write("\t\t//datagrid初始化 \n");
      out.write("\t    $('#dataList').datagrid({ \n");
      out.write("\t        title:'班级列表', \n");
      out.write("\t        iconCls:'icon-more',//图标 \n");
      out.write("\t        border: true, \n");
      out.write("\t        collapsible: false,//是否可折叠的 \n");
      out.write("\t        fit: true,//自动大小 \n");
      out.write("\t        method: \"post\",\n");
      out.write("\t        url:\"ClazzServlet?method=ClazzDetailList&t=\"+new Date().getTime(),\n");
      out.write("\t        idField:'id', \n");
      out.write("\t        singleSelect: true,//是否单选 \n");
      out.write("\t        pagination: true,//分页控件 \n");
      out.write("\t        rownumbers: true,//行号 \n");
      out.write("\t        sortName: 'id',\n");
      out.write("\t        sortOrder: 'DESC', \n");
      out.write("\t        remoteSort: false,\n");
      out.write("\t        columns: [[  \n");
      out.write("\t\t\t\t{field:'chk',checkbox: true,width:50},\n");
      out.write(" \t\t        {field:'id',title:'ID',width:50, sortable: true},    \n");
      out.write(" \t\t        {field:'name',title:'班级名称',width:200},\n");
      out.write(" \t\t        {field:'grade',title:'所属年级',width:100, \n");
      out.write(" \t\t        \tformatter: function(value,row,index){\n");
      out.write(" \t\t\t\t\t\tif (row.grade){\n");
      out.write(" \t\t\t\t\t\t\treturn row.grade.name;\n");
      out.write(" \t\t\t\t\t\t} else {\n");
      out.write(" \t\t\t\t\t\t\treturn value;\n");
      out.write(" \t\t\t\t\t\t}\n");
      out.write(" \t\t\t\t\t}\t\n");
      out.write(" \t\t        },\n");
      out.write("\t \t\t]], \n");
      out.write("\t        toolbar: \"#toolbar\"\n");
      out.write("\t    }); \n");
      out.write("\t    //设置分页控件 \n");
      out.write("\t    var p = $('#dataList').datagrid('getPager'); \n");
      out.write("\t    $(p).pagination({ \n");
      out.write("\t        pageSize: 10,//每页显示的记录条数，默认为10 \n");
      out.write("\t        pageList: [10,20,30,50,100],//可以设置每页记录条数的列表 \n");
      out.write("\t        beforePageText: '第',//页数文本框前显示的汉字 \n");
      out.write("\t        afterPageText: '页    共 {pages} 页', \n");
      out.write("\t        displayMsg: '当前显示 {from} - {to} 条记录   共 {total} 条记录', \n");
      out.write("\t    });\n");
      out.write("\t    //设置工具类按钮\n");
      out.write("\t    $(\"#add\").click(function(){\n");
      out.write("\t    \t$(\"#addDialog\").dialog(\"open\");\n");
      out.write("\t    });\n");
      out.write("\t    //删除\n");
      out.write("\t    $(\"#delete\").click(function(){\n");
      out.write("\t    \tvar selectRow = $(\"#dataList\").datagrid(\"getSelected\");\n");
      out.write("        \tif(selectRow == null){\n");
      out.write("            \t$.messager.alert(\"消息提醒\", \"请选择数据进行删除!\", \"warning\");\n");
      out.write("            } else{\n");
      out.write("            \tvar clazzid = selectRow.id;\n");
      out.write("            \t$.messager.confirm(\"消息提醒\", \"将删除与班级相关的所有数据(包括学生)，确认继续？\", function(r){\n");
      out.write("            \t\tif(r){\n");
      out.write("            \t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t\t\ttype: \"post\",\n");
      out.write("\t\t\t\t\t\t\turl: \"ClazzServlet?method=DeleteClazz\",\n");
      out.write("\t\t\t\t\t\t\tdata: {clazzid: clazzid},\n");
      out.write("\t\t\t\t\t\t\tsuccess: function(msg){\n");
      out.write("\t\t\t\t\t\t\t\tif(msg == \"success\"){\n");
      out.write("\t\t\t\t\t\t\t\t\t$.messager.alert(\"消息提醒\",\"删除成功!\",\"info\");\n");
      out.write("\t\t\t\t\t\t\t\t\t//刷新表格\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#dataList\").datagrid(\"reload\");\n");
      out.write("\t\t\t\t\t\t\t\t} else{\n");
      out.write("\t\t\t\t\t\t\t\t\t$.messager.alert(\"消息提醒\",\"删除失败!\",\"warning\");\n");
      out.write("\t\t\t\t\t\t\t\t\treturn;\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("            \t\t}\n");
      out.write("            \t});\n");
      out.write("            }\n");
      out.write("\t    });\n");
      out.write("\t    \n");
      out.write("\t  \t//年级下拉框\n");
      out.write("\t  \t$(\"#gradeList\").combobox({\n");
      out.write("\t  \t\twidth: \"150\",\n");
      out.write("\t  \t\theight: \"25\",\n");
      out.write("\t  \t\tvalueField: \"id\",\n");
      out.write("\t  \t\ttextField: \"name\",\n");
      out.write("\t  \t\tmultiple: false, //可多选\n");
      out.write("\t  \t\teditable: false, //不可编辑\n");
      out.write("\t  \t\tmethod: \"post\",\n");
      out.write("\t  \t\turl: \"GradeServlet?method=GradeList&t=\"+new Date().getTime(),\n");
      out.write("\t  \t\tonChange: function(newValue, oldValue){\n");
      out.write("\t  \t\t\t$('#dataList').datagrid(\"options\").queryParams = {gradeid: newValue};\n");
      out.write("\t  \t\t\t$('#dataList').datagrid(\"reload\");\n");
      out.write("\t  \t\t}\n");
      out.write("\t  \t});\n");
      out.write("\t    \n");
      out.write("\t  \t//添加年级下拉框\n");
      out.write("\t  \t$(\"#add_gradeList\").combobox({\n");
      out.write("\t  \t\tvalueField: \"id\",\n");
      out.write("\t  \t\ttextField: \"name\",\n");
      out.write("\t  \t\tmultiple: false, //可多选\n");
      out.write("\t  \t\teditable: false, //不可编辑\n");
      out.write("\t  \t\tmethod: \"post\",\n");
      out.write("\t  \t\turl: \"GradeServlet?method=GradeList&t=\"+new Date().getTime(),\n");
      out.write("\t  \t\tonLoadSuccess: function(){\n");
      out.write("\t\t  \t\t//默认选择第一条数据\n");
      out.write("\t\t\t\tvar data = $(this).combobox(\"getData\");\n");
      out.write("\t\t\t\t$(this).combobox(\"setValue\", data[0].id);\n");
      out.write("\t  \t\t}\n");
      out.write("\t  \t});\n");
      out.write("\t  \t\n");
      out.write("\t  \t//设置添加学生窗口\n");
      out.write("\t    $(\"#addDialog\").dialog({\n");
      out.write("\t    \ttitle: \"添加班级\",\n");
      out.write("\t    \twidth: 500,\n");
      out.write("\t    \theight: 400,\n");
      out.write("\t    \ticonCls: \"icon-add\",\n");
      out.write("\t    \tmodal: true,\n");
      out.write("\t    \tcollapsible: false,\n");
      out.write("\t    \tminimizable: false,\n");
      out.write("\t    \tmaximizable: false,\n");
      out.write("\t    \tdraggable: true,\n");
      out.write("\t    \tclosed: true,\n");
      out.write("\t    \tbuttons: [\n");
      out.write("\t    \t\t{\n");
      out.write("\t\t\t\t\ttext:'添加',\n");
      out.write("\t\t\t\t\tplain: true,\n");
      out.write("\t\t\t\t\ticonCls:'icon-add',\n");
      out.write("\t\t\t\t\thandler:function(){\n");
      out.write("\t\t\t\t\t\tvar validate = $(\"#addForm\").form(\"validate\");\n");
      out.write("\t\t\t\t\t\tif(!validate){\n");
      out.write("\t\t\t\t\t\t\t$.messager.alert(\"消息提醒\",\"请检查你输入的数据!\",\"warning\");\n");
      out.write("\t\t\t\t\t\t\treturn;\n");
      out.write("\t\t\t\t\t\t} else{\n");
      out.write("\t\t\t\t\t\t\tvar gradeid = $(\"#add_gradeList\").combobox(\"getValue\");\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t\t\t\ttype: \"post\",\n");
      out.write("\t\t\t\t\t\t\t\turl: \"ClazzServlet?method=AddClazz\",\n");
      out.write("\t\t\t\t\t\t\t\tdata: $(\"#addForm\").serialize(),\n");
      out.write("\t\t\t\t\t\t\t\tsuccess: function(msg){\n");
      out.write("\t\t\t\t\t\t\t\t\tif(msg == \"success\"){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$.messager.alert(\"消息提醒\",\"添加成功!\",\"info\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//关闭窗口\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#addDialog\").dialog(\"close\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//清空原表格数据\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#add_name\").textbox('setValue', \"\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//重新刷新页面数据\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t$('#gradeList').combobox(\"setValue\", gradeid);\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t$('#dataList').datagrid(\"reload\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t} else{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$.messager.alert(\"消息提醒\",\"添加失败!\",\"warning\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\treturn;\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\ttext:'重置',\n");
      out.write("\t\t\t\t\tplain: true,\n");
      out.write("\t\t\t\t\ticonCls:'icon-reload',\n");
      out.write("\t\t\t\t\thandler:function(){\n");
      out.write("\t\t\t\t\t\t$(\"#add_name\").textbox('setValue', \"\");\n");
      out.write("\t\t\t\t\t\t//重新加载年级\n");
      out.write("\t\t\t\t\t\t$(\"#add_gradeList\").combobox(\"reload\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t]\n");
      out.write("\t    });\n");
      out.write("\t  \t\n");
      out.write("\t});\n");
      out.write("\t</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- 数据列表 -->\n");
      out.write("\t<table id=\"dataList\" cellspacing=\"0\" cellpadding=\"0\"> \n");
      out.write("\t</table> \n");
      out.write("\t\n");
      out.write("\t<!-- 工具栏 -->\n");
      out.write("\t<div id=\"toolbar\">\n");
      out.write("\t\t<div style=\"float: left;\"><a id=\"add\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add',plain:true\">添加</a></div>\n");
      out.write("\t\t\t<div style=\"float: left;\" class=\"datagrid-btn-separator\"></div>\n");
      out.write("\t\t<div style=\"float: left; margin-right: 10px;\"><a id=\"delete\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-some-delete',plain:true\">删除</a></div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div style=\"margin: 0 10px 0 10px\">年级：<input id=\"gradeList\" class=\"easyui-textbox\" name=\"grade\" /></div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<!-- 添加窗口 -->\n");
      out.write("\t<div id=\"addDialog\" style=\"padding: 10px\">  \n");
      out.write("    \t<form id=\"addForm\" method=\"post\">\n");
      out.write("\t    \t<table cellpadding=\"8\" >\n");
      out.write("\t    \t\t<tr>\n");
      out.write("\t    \t\t\t<td>班级名称:</td>\n");
      out.write("\t    \t\t\t<td><input id=\"add_name\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"name\"  validType=\"repeat_clazz['#add_gradeList']\" data-options=\"required:true, missingMessage:'不能为空'\" /></td>\n");
      out.write("\t    \t\t</tr>\n");
      out.write("\t    \t\t<tr>\n");
      out.write("\t    \t\t\t<td>所属年级:</td>\n");
      out.write("\t    \t\t\t<td><select id=\"add_gradeList\" style=\"width: 200px; height: 30px;\" name=\"gradeid\" ></select></td>\n");
      out.write("\t    \t\t</tr>\n");
      out.write("\t    \t</table>\n");
      out.write("\t    </form>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
