/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2018-11-02 12:31:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"renderer\" content=\"webkit|ie-comp|ie-stand\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\" />\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\"/>\n");
      out.write("<link rel=\"bookmark\" href=\"favicon.ico\"/>\n");
      out.write("<link href=\"h-ui/css/H-ui.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"h-ui/css/H-ui.login.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"h-ui/lib/icheck/icheck.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"h-ui/lib/Hui-iconfont/1.0.1/iconfont.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script> \n");
      out.write("<script type=\"text/javascript\" src=\"h-ui/js/H-ui.js\"></script> \n");
      out.write("<script type=\"text/javascript\" src=\"h-ui/lib/icheck/jquery.icheck.min.js\"></script> \n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(function(){\n");
      out.write("\t\t//点击图片切换验证码\n");
      out.write("\t\t$(\"#vcodeImg\").click(function(){\n");
      out.write("\t\t\tthis.src=\"LoginServlet?method=GetVcode&t=\"+new Date().getTime();\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t//登录\n");
      out.write("\t\t$(\"#submitBtn\").click(function(){\n");
      out.write("\t\t\tif($(\"#radio-2\").attr(\"checked\") && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${systemInfo.forbidStudent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == 1){\n");
      out.write("\t\t\t\t$.messager.alert(\"消息提醒\", \"学生暂不能登录系统！\", \"warning\");\n");
      out.write("\t\t\t\treturn;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif($(\"#radio-3\").attr(\"checked\") && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${systemInfo.forbidTeacher}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == 1){\n");
      out.write("\t\t\t\t$.messager.alert(\"消息提醒\", \"教师暂不能登录系统！\", \"warning\");\n");
      out.write("\t\t\t\treturn;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar data = $(\"#form\").serialize();\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype: \"post\",\n");
      out.write("\t\t\t\turl: \"LoginServlet?method=Login\",\n");
      out.write("\t\t\t\tdata: data, \n");
      out.write("\t\t\t\tdataType: \"text\", //返回数据类型\n");
      out.write("\t\t\t\tsuccess: function(msg){\n");
      out.write("\t\t\t\t\tif(\"vcodeError\" == msg){\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"消息提醒\", \"验证码错误!\", \"warning\");\n");
      out.write("\t\t\t\t\t\t$(\"#vcodeImg\").click();//切换验证码\n");
      out.write("\t\t\t\t\t\t$(\"input[name='vcode']\").val(\"\");//清空验证码输入框\n");
      out.write("\t\t\t\t\t} else if(\"loginError\" == msg){\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"消息提醒\", \"用户名或密码错误!\", \"warning\");\n");
      out.write("\t\t\t\t\t\t$(\"#vcodeImg\").click();//切换验证码\n");
      out.write("\t\t\t\t\t\t$(\"input[name='vcode']\").val(\"\");//清空验证码输入框\n");
      out.write("\t\t\t\t\t} else if(\"admin\" == msg){\n");
      out.write("\t\t\t\t\t\twindow.location.href = \"SystemServlet?method=toAdminView\";\n");
      out.write("\t\t\t\t\t} else if(\"student\" == msg){\n");
      out.write("\t\t\t\t\t\twindow.location.href = \"SystemServlet?method=toStudentView\";\n");
      out.write("\t\t\t\t\t} else if(\"teacher\" == msg){\n");
      out.write("\t\t\t\t\t\twindow.location.href = \"SystemServlet?method=toTeacherView\";\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t//设置复选框\n");
      out.write("\t\t$(\".skin-minimal input\").iCheck({\n");
      out.write("\t\t\tradioClass: 'iradio-blue',\n");
      out.write("\t\t\tincreaseArea: '25%'\n");
      out.write("\t\t});\n");
      out.write("\t})\n");
      out.write("</script> \n");
      out.write("<title>登录|学生成绩管理系统</title>\n");
      out.write("<meta name=\"keywords\" content=\"学生成绩管理系统\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"header\" style=\"padding: 0;\">\n");
      out.write("\t<h2 style=\"color: white; width: 400px; height: 60px; line-height: 60px; margin: 0 0 0 30px; padding: 0;\">学生成绩管理系统</h2>\n");
      out.write("</div>\n");
      out.write("<div class=\"loginWraper\">\n");
      out.write("  <div id=\"loginform\" class=\"loginBox\">\n");
      out.write("    <form id=\"form\" class=\"form form-horizontal\" method=\"post\">\n");
      out.write("      <div class=\"row cl\">\n");
      out.write("        <label class=\"form-label col-3\"><i class=\"Hui-iconfont\">&#xe60d;</i></label>\n");
      out.write("        <div class=\"formControls col-8\">\n");
      out.write("          <input id=\"\" name=\"account\" type=\"text\" placeholder=\"账户\" class=\"input-text size-L\">\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row cl\">\n");
      out.write("        <label class=\"form-label col-3\"><i class=\"Hui-iconfont\">&#xe60e;</i></label>\n");
      out.write("        <div class=\"formControls col-8\">\n");
      out.write("          <input id=\"\" name=\"password\" type=\"password\" placeholder=\"密码\" class=\"input-text size-L\">\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row cl\">\n");
      out.write("        <div class=\"formControls col-8 col-offset-3\">\n");
      out.write("          <input class=\"input-text size-L\" name=\"vcode\" type=\"text\" placeholder=\"请输入验证码\" style=\"width: 200px;\">\n");
      out.write("          <img title=\"点击图片切换验证码\" id=\"vcodeImg\" src=\"LoginServlet?method=GetVCode\"></div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <div class=\"mt-20 skin-minimal\" style=\"text-align: center;\">\n");
      out.write("\t\t<div class=\"radio-box\">\n");
      out.write("\t\t\t<input type=\"radio\" id=\"radio-2\" name=\"type\" checked value=\"2\" />\n");
      out.write("\t\t\t<label for=\"radio-1\">学生</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"radio-box\">\n");
      out.write("\t\t\t<input type=\"radio\" id=\"radio-3\" name=\"type\" value=\"3\" />\n");
      out.write("\t\t\t<label for=\"radio-2\">老师</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"radio-box\">\n");
      out.write("\t\t\t<input type=\"radio\" id=\"radio-1\" name=\"type\" value=\"1\" />\n");
      out.write("\t\t\t<label for=\"radio-3\">管理员</label>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("      \n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"formControls col-8 col-offset-3\">\n");
      out.write("          <input id=\"submitBtn\" type=\"button\" class=\"btn btn-success radius size-L\" value=\"&nbsp;登&nbsp;&nbsp;&nbsp;&nbsp;录&nbsp;\">\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<div class=\"footer\">Copyright &nbsp; SWU @ Lizhou </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
