/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2018-11-02 12:32:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("    <title>学生成绩管理系统 管理员后台</title>\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico\"/>\n");
      out.write("\t<link rel=\"bookmark\" href=\"favicon.ico\"/>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/css/default.css\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\" />\n");
      out.write("    <script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src='easyui/js/outlook2.js'> </script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("\t var _menus = {\"menus\":[\n");
      out.write("\t\t\t\t\t\t{\"menuid\":\"1\",\"icon\":\"\",\"menuname\":\"成绩统计分析\",\n");
      out.write("\t\t\t\t\t\t\t\"menus\":[\n");
      out.write("\t\t\t\t\t\t\t\t\t{\"menuid\":\"11\",\"menuname\":\"考试列表\",\"icon\":\"icon-exam\",\"url\":\"ExamServlet?method=toExamListView\"}\n");
      out.write("\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t{\"menuid\":\"2\",\"icon\":\"\",\"menuname\":\"学生信息管理\",\n");
      out.write("\t\t\t\t\t\t\t\"menus\":[\n");
      out.write("\t\t\t\t\t\t\t\t\t{\"menuid\":\"21\",\"menuname\":\"学生列表\",\"icon\":\"icon-user-student\",\"url\":\"StudentServlet?method=toStudentListView\"},\n");
      out.write("\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t{\"menuid\":\"3\",\"icon\":\"\",\"menuname\":\"教师信息管理\",\n");
      out.write("\t\t\t\t\t\t\t\"menus\":[\n");
      out.write("\t\t\t\t\t\t\t\t\t{\"menuid\":\"31\",\"menuname\":\"教师列表\",\"icon\":\"icon-user-teacher\",\"url\":\"TeacherServlet?method=toTeacherListView\"},\n");
      out.write("\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t{\"menuid\":\"4\",\"icon\":\"\",\"menuname\":\"基础信息管理\",\n");
      out.write("\t\t\t\t\t\t\t\"menus\":[\n");
      out.write("\t\t\t\t\t\t\t\t\t{\"menuid\":\"41\",\"menuname\":\"年级列表\",\"icon\":\"icon-world\",\"url\":\"GradeServlet?method=toGradeListView\"},\n");
      out.write("\t\t\t\t\t\t\t\t\t{\"menuid\":\"42\",\"menuname\":\"班级列表\",\"icon\":\"icon-house\",\"url\":\"ClazzServlet?method=toClazzListView\"},\n");
      out.write("\t\t\t\t\t\t\t\t\t{\"menuid\":\"43\",\"menuname\":\"课程列表\",\"icon\":\"icon-book-open\",\"url\":\"CourseServlet?method=toCourseListView\"}\n");
      out.write("\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t{\"menuid\":\"5\",\"icon\":\"\",\"menuname\":\"系统管理\",\n");
      out.write("\t\t\t\t\t\t\t\"menus\":[\n");
      out.write("\t\t\t\t\t\t\t        {\"menuid\":\"51\",\"menuname\":\"系统设置\",\"icon\":\"icon-set\",\"url\":\"SystemServlet?method=toAdminPersonalView\"},\n");
      out.write("\t\t\t\t\t\t\t\t]\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t]};\n");
      out.write("\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\"easyui-layout\" style=\"overflow-y: hidden\"  scroll=\"no\">\n");
      out.write("\t<noscript>\n");
      out.write("\t\t<div style=\" position:absolute; z-index:100000; height:2046px;top:0px;left:0px; width:100%; background:white; text-align:center;\">\n");
      out.write("\t\t    <img src=\"images/noscript.gif\" alt='抱歉，请开启脚本支持！' />\n");
      out.write("\t\t</div>\n");
      out.write("\t</noscript>\n");
      out.write("    <div region=\"north\" split=\"true\" border=\"false\" style=\"overflow: hidden; height: 30px;\n");
      out.write("        background: url(images/layout-browser-hd-bg.gif) #7f99be repeat-x center 50%;\n");
      out.write("        line-height: 20px;color: #fff; font-family: Verdana, 微软雅黑,黑体\">\n");
      out.write("        <span style=\"float:right; padding-right:20px;\" class=\"head\"><span style=\"color:red; font-weight:bold;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&nbsp;</span>您好&nbsp;&nbsp;&nbsp;<a href=\"SystemServlet?method=LoginOut\" id=\"loginOut\">安全退出</a></span>\n");
      out.write("        <span style=\"padding-left:10px; font-size: 16px; \">SWU学生信息管理系统</span>\n");
      out.write("    </div>\n");
      out.write("    <div region=\"south\" split=\"true\" style=\"height: 30px; background: #D2E0F2; \">\n");
      out.write("        <div class=\"footer\">Copyright &copy; SWU By 伯姜洲</div>\n");
      out.write("    </div>\n");
      out.write("    <div region=\"west\" hide=\"true\" split=\"true\" title=\"导航菜单\" style=\"width:180px;\" id=\"west\">\n");
      out.write("\t<div id=\"nav\" class=\"easyui-accordion\" fit=\"true\" border=\"false\">\n");
      out.write("\t\t<!--  导航内容 -->\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("    </div>\n");
      out.write("    <div id=\"mainPanle\" region=\"center\" style=\"background: #eee; overflow-y:hidden\">\n");
      out.write("        <div id=\"tabs\" class=\"easyui-tabs\"  fit=\"true\" border=\"false\" >\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/admin/welcome.jsp", out, false);
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("    </div>\n");
      out.write("\t\n");
      out.write("\t<iframe width=0 height=0 src=\"refresh.jsp\"></iframe>\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
